### ISSUE TITLE
讨论下 PowJS 的做法

### ISSUE THREAD

**Issue by achun** [Javey/javey.github.io#1]
嗨!
终于看到直接从 DOM 入手的模板方案了, 认为 Vdt 的语法还可以进化.
我们知道 HTML 在运行时是以 DOM 对象存在的, DOM 天生就具有结构性.
而解析 HTML 生成 DOM 可由平台环境完成.
基于此, 我设计了 [PowJS](https://github.com/powjs/powjs).
然, 由于时间关系该作品还没有 1.0.
我希望有其它项目也使用 PowJS 的思想, 思想是跨项目的.
您对此有什么想法呢?

**Comment by Javey** [comment]
@achun 赞～我研究一下

**Comment by Javey** [comment]
Hi @achun 看了一下你的项目,由于没找到实际能运行例子,所以我的大致理解是:你想通过写带逻辑的纯HTML,来完全摆脱js？

**Comment by achun** [comment]
@Javey PowJS 的思路是不写解析器, 因为完全采用标准的 HTML 格式, 所以模板是可以被浏览器直接渲染的. 这样只需要遍历 DOM 数, 把指令属性名翻译成 js 语句, 属性值完全采用原生 js 语法, 因为已经生成了 DOM , 除了那些需要根据条件删除的的节点, 其他节点都已经生成了(当然循环需要再处理下), 绑定 this 节点之类的操作都是实时进行的.

如果可能的话, 建议 Vdt 吸收这个思路: 无解析器, 利用环境去渲染 DOM.
至于具体指令怎么写, 我想会有多种不同做法, 只要可行就好. 当然最终还是要翻译到 JS 的.

**Comment by Javey** [comment]
完全采用标准的HTML格式，然后翻译成JS。这似乎是模板通用的做法，只不过有写模板引擎能在模板中直接书写js代码，例如：[marko-js/marko](https://github.com/marko-js/marko)，有些如你所说为声明式的，例如：Angular和Vue中的模板（当然他们不是单纯的模板引擎）。Vdt能够在模板中写JS的，这提供了一些便利，但有时也造成困扰，由于太灵活，一旦JS报错，可能导致整个模板崩溃。
我想语法应该是其次，仅仅只是为书写带来便利性，最主要的是有一种方法，实现在数据变更时更新模板。@achun 你觉得呢？

**Comment by achun** [comment]
@Javey 估计是我没有阐述清楚, 对比一下

这是 Vdt 和其它模板引擎使用的语法

```html
<div v-if={a === 1}>一</div>
```

这是 PowJS 使用的语法

```html
<div v-if="a === 1">一</div>
```
区别在于属性中, PowJS 使用的是双引号包裹指令代码. textContent 中的写法没有区别.
也就是说 PowJS 的写法是可以直接被浏览器渲染的, 渲染后的  DOM 就是模板原型, 解析只剩下 textContent 中的部分.

另外:
我也是偏向使用原生 JS 语法的(这和模板语法无关).
对于使用者来说, 多数是不太关心语法的, 这点也是事实.

**Comment by Javey** [comment]
似乎明白了你的意思，不知理解的对不对

的确，Vdt模板如果直接当做html渲染是有问题的，例如：
```html
<div v-if={a === 1}>一</div>
```
由于属性值存在空格，所以不能正常渲染。如果要在html中书写模板，只能借助一些特殊标签（script，textarea等）来办到，例如：
```html
<script type="text/vdt">
    <div v-if={a === 1}>一</div>
</script>
```
这种设计的一个好处就是，可以保持所有的属性名不变，而通过属性值的写法来区分 __动态属性__ 和 __静态属性__。例如：
```html
静态属性 <a href="/"></a>
动态属性 <a href={ href }></a>
```

当然另外一种思路是，保持模板为标准的html写法，这时可能就要在属性名上做文章，来区分 __动态属性__ 和  __静态属性__ 了。
```html
Angular   <a href="/"></a>      <a ng-href="href"></a>
Vue       <a href="/"></a>      <a :href="href"></a>
```

@achun 所以你是更倾向于第二种写法吗？

**Comment by achun** [comment]
Hi @Javey 你终于知道我要说啥了, 这个怪我前面没有直入主题.
是的, 对于属性中的模板语法, 我更倾向于第二种写法( PowJS 的写法).
首先无论哪一种写法最终都要生成 JS 控制代码的. 传统写法下的生成就不讨论了.
PowJS 的那种写法下, 指令代码经函数化后被直接附加到 DOM 模板节点上, 这个可以称作 DOM 模板指令事件.
加载数据时, 也只是传递给 DOM 模板的第一个节点事件而已, 这样一层层传递, 从而生成渲染 view.
至于这个 view 是新生成的, 还是直接基于 DOM 模板进化来的, 这属于细节.

这个方案不只是省略了解析, 对节点事件绑定上也有很大优势.
可以预见, 这个东西在很多场景中, 类似 jQuery 这样的的库就失去意义, 因为节点和事件直接直观绑定了, 除非是从外部代码引入的操作才需要定位节点.

**Comment by achun** [comment]
@Javey 你看下 https://github.com/powjs/powjs/blob/master/src/directives.js 的代码
当然这只是为了说明 PowJS 的思路,  这个指令系统的设计很初级, 毕竟一直没有时间做出 1.0, 如果你做的话, 估计还需要对指令系统进行整体规划.

我的目的: 推荐 DOM 模板的思路, 并非要合并 Vdt 和 PowJS, 哎, 遗憾, 时间不够, 不然我就直接参与贡献了.

**Comment by achun** [comment]
另外聊点场外, 传统模板的做法, 2008 年的时候我就做了 https://github.com/achun/jCT 这个.
当时 jCT 采用原生 js 语法的方案有些超前, 毕竟那时候的模板设计都是玩独立语法, 然后翻译到宿主语言的.

但是现在不同了, 大家已经普遍认同原生宿主语言语法了.

所以当我看到 Vdt 的时候, 立马感觉到 Vdt 也是期望能更好的绑定 view 中的节点, 我就知道 PowJS 的做法很可能被你接受, 因为这种方法更容易绑定节点

**Comment by Javey** [comment]
当时设计Vdt的时候，也就是想要一个能够**更新**的模板引擎，很可惜当时似乎没有找到类似的，所以就自己做了个。但毕竟我一个人精力、水平都有限，非常期待你的加入 @achun

**Comment by achun** [comment]
哈，我终于有时间完成他了。
https://github.com/powjs/powjs
精简到不能再精简了。在DOM 上解析，可导出。
这里有个例子
https://gist.github.com/achun/232117d182eee78765ba3156eaae336b

**Comment by Javey** [comment]
@achun 国庆节快乐哈～
看了你的实现，的确很精简。但咱们存在设计上的分歧

1. 语法上，PowJS倾向于采用html标准，Vdt倾向于JSX标准，html只是辅助。
2. 功能上，PowJS只支持渲染，Vdt支持渲染和更新。

单纯讨论语法的话，向html标准靠拢，的确能提供很多便利，所以Vdt也提供了v-if（对应if）v-for（对应each）等指令来简化模板书写。对于PowJS中的do/let就要考虑下必要性了，会不会造成模板可读性变低呢？另外skip和end好像用if/else-if/else来解决比较好（Vdt提供了对应的指令v-if/v-else-if/v-else），break这个指令在for循环中很有必要，可以借鉴下。

其实从不从DOM上解析模板，本质都是一样的，即使你将模板写在DOM中，在没渲染之前也是要隐藏的，最终都是获取模板字符串来解析。
